version: '3.8'

services:
  ecommerceapp.webui:
    container_name: webui_container
    image: hikdogru/ecommerceappwebui:latest
    build:
      context: .
      dockerfile: src/ECommerceApp.WebUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - MongoConnectionString__Connection=mongodb://mongo:27017
      - MongoConnectionString__DatabaseName=ecommerceapp      
    ports:
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
     - mongo
    networks:
    - backend
  mongo:
    container_name: mongo_container
    image: mongo:latest
    ports:     
     - "27017:27017"
    volumes:
     - ${APPDATA}/MongoDb:/data/db
    networks:
     - backend
    restart: always

networks:
   backend:
     driver: bridge
     external: true
